# MAPPO parameters

algo_args:
  batch_episode:  10
  batch_mode: "complete_episodes"
  lr: 0.00005
  iteration: 4
  entropy_coeff: 0.01
  clip_param: 0.2
  vf_clip_param: 20.0

#  config.update({
#        "seed": 1,
#        "env": args.map,
#        "horizon": 1000,
#        "num_sgd_iter": 5,  # ppo-epoch
#        "train_batch_size": 4000,
#        "sgd_minibatch_size": sgd_minibatch_size,
#        "lr": 5e-5,
#        "grad_clip": 10,
#        "clip_param": 0.3,
#        "model": {
#            "custom_model": "{}_CentralizedCritic".format(args.neural_arch),
#            "custom_model_config": {
#                "agent_num": env_config["ally_num"],
#                "state_dim": env_config["state_dim"],
#                "normal_value": True
#            },
#            "vf_share_layers": True,
#        },
#    })