# MAPPO parameters

#algo_args:
#  batch_episode:  10
#  batch_mode: "complete_episodes"
#  lr: 0.0005
#  iteration: 4
#  entropy_coeff: 0.01
#  clip_param: 0.2
#  vf_clip_param: 20.0

algo_args:
  batch_episode:  10
  batch_mode: "complete_episodes"
  iteration: 5
  horizon: 1000
  num_sgd_iter: 5  # ppo-epoch
  train_batch_size: 4000
  sgd_minibatch_size: 128
  vf_clip_param: 20.0
  grad_clip: 10
  clip_param: 0.3  # ppo-clip
  use_critic: True
  gamma: 0.99
  normal_value: True
  vf_share_layers: True
  critic_lr: 5e-3
  lr: 5e-6
  lr_sh_min: 0
  lr_sh_max: 5e-6
  lr_sh_step: 1e7
  lr_min: 1e-8
  entropy_coeff: 0.01

