# HAPPO parameters

algo_args:
  batch_episode:  10
  batch_mode: "complete_episodes"
  iteration: 5
  horizon: 1000
  num_sgd_iter: 5
  train_batch_size: 4000
  sgd_minibatch_size: 128
  vf_clip_param: 20.0
  grad_clip: 10
  clip_param: 0.3
  use_critic: True
  gamma: 0.99
  normal_value: True
  vf_share_layers: True
  critic_lr: 0.005
  lr: 0.000005
  entropy_coeff: 0.01

