env: football

env_args:
  map_name: "academy_empty_goal" # other available maps can be found in IL/envs/football_rllib.py
  logdir: ""
  render: False
  dump_frequency: 0

core_arch: "lstm" # LSTM, Transformer
mask_flag: False
global_state_flag: False

