# TRPO parameters

algo_args:
  batch_episode: 5
  batch_mode: complete_episodes
  iteration: 4
  horizon: 1000
  num_sgd_iter: 5  # ppo-epoch
  train_batch_size: 4000
  sgd_minibatch_size: 128
  grad_clip: 10
  clip_param: 0.3  # ppo-clip
  use_critic: True
  gamma: 0.99
  normal_value: True
  vf_share_layers: True
  critic_lr: 0.01
  lr: 0.00005
  lr_sh_min: 0
  lr_sh_max: 0.00005
  lr_sh_step: 999999
  lr_min: 0.00000001