name: test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install pytest-cov
        pip install ray==1.8.0
        pip install ray[tune]
        pip install ray[rllib]
        pip install icecream
        pip install pettingzoo==1.12.0
        pip install pettingzoo[mpe]
        pip install supersuit
        pip install gym==0.21.0
        pip install importlib-metadata==4.13.0
        pip install -e .
    - name: Unit tests
      run: |
        mkdir -p test_data
        pytest --cov-report=xml --cov=MARLlib tests -p no:warnings -v